//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.CMD.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitness.CMD.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;калорийность&quot;.
        /// </summary>
        internal static string calories_msg {
            get {
                return ResourceManager.GetString("calories_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;углеводы&quot;.
        /// </summary>
        internal static string carbs_msg {
            get {
                return ResourceManager.GetString("carbs_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Введите пол: &quot;.
        /// </summary>
        internal static string choosegender_msg {
            get {
                return ResourceManager.GetString("choosegender_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;что вы хотите сделать: &quot;.
        /// </summary>
        internal static string choosemove_msg {
            get {
                return ResourceManager.GetString("choosemove_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Введите дату своего рождения dd.MM.yyyy&quot;.
        /// </summary>
        internal static string datechoose_msg {
            get {
                return ResourceManager.GetString("datechoose_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Е - ввести приём пищи&quot;.
        /// </summary>
        internal static string eismakechoose_msg {
            get {
                return ResourceManager.GetString("eismakechoose_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Введите имя пользователя&quot;.
        /// </summary>
        internal static string entername_msg {
            get {
                return ResourceManager.GetString("entername_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;жиры&quot;.
        /// </summary>
        internal static string fats_msg {
            get {
                return ResourceManager.GetString("fats_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Введите имя продукта: &quot;.
        /// </summary>
        internal static string name_msg {
            get {
                return ResourceManager.GetString("name_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;белки&quot;.
        /// </summary>
        internal static string prots_msg {
            get {
                return ResourceManager.GetString("prots_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Повторите ввод&quot;.
        /// </summary>
        internal static string repeatinsert_msg {
            get {
                return ResourceManager.GetString("repeatinsert_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;вес порции&quot;.
        /// </summary>
        internal static string weight_msg {
            get {
                return ResourceManager.GetString("weight_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Вас приветствует приложение Fitness&quot;.
        /// </summary>
        internal static string welcome_msg {
            get {
                return ResourceManager.GetString("welcome_msg", resourceCulture);
            }
        }
    }
}
